# -*- coding: utf-8 -*-
"""adult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwZ2YEoc_UmSe1SWIdY_Q0lJZ2Dvn3hy
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(next(iter(uploaded)))
df.head()

# Replace ? with NaN
df.replace("?", np.nan, inplace=True)

# Fill missing categorical values with mode
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

adult_encoded = pd.get_dummies(df, drop_first=True)
adult_encoded.head()

num_cols = adult_encoded.select_dtypes(include=np.number)

Q1 = num_cols.quantile(0.25)
Q3 = num_cols.quantile(0.75)
IQR = Q3 - Q1

adult_cleaned = adult_encoded[
    ~((num_cols < (Q1 - 1.5 * IQR)) |
      (num_cols > (Q3 + 1.5 * IQR))).any(axis=1)
]

from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
adult_minmax = minmax.fit_transform(adult_cleaned)

adult_minmax = pd.DataFrame(adult_minmax, columns=adult_cleaned.columns)
adult_minmax.head()

from sklearn.preprocessing import StandardScaler

std = StandardScaler()
adult_standardized = std.fit_transform(adult_cleaned)

adult_standardized = pd.DataFrame(adult_standardized, columns=adult_cleaned.columns)
adult_standardized.head()