# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg2VQ-T-43hw2kBlI2aPgRH56TAfq43a
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(next(iter(uploaded)))
df.head()

from pandas.core.frame import DataFrame
# Check missing values
# Check missing values
df.isnull().sum()
# Fill numerical missing values with mean
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())
# Fill categorical missing values with mode
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

diabetes_encoded = pd.get_dummies(df, columns=['Gender', 'CLASS'], drop_first=True)
diabetes_encoded.head()

# Remove outliers using IQR method
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

diabetes = df[~((df < (Q1 - 1.5 * IQR)) |
                      (df > (Q3 + 1.5 * IQR))).any(axis=1)]
print(diabetes)

# from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()
diabetes_minmax = minmax_scaler.fit_transform(diabetes)

diabetes_minmax = pd.DataFrame(diabetes_minmax, columns=diabetes.columns)
diabetes_minmax.head()

standard_scaler = StandardScaler()
diabetes_standardized = standard_scaler.fit_transform(diabetes)

diabetes_standardized = pd.DataFrame(diabetes_standardized, columns=diabetes.columns)
diabetes_standardized.head()

