# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSnx4LHmm6hidZFNt_8IMXM3B3gPTBh3
"""

# Basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ML utilities
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin

url = "https://media.geeksforgeeks.org/wp-content/uploads/20240319120216/housing.csv"
housing = pd.read_csv(url)

housing.head()

housing.info()
housing.describe()

housing.hist(bins=50, figsize=(20,15))
plt.show()

train_set, test_set = train_test_split(
    housing, test_size=0.2, random_state=42
)
housing["income_cat"] = pd.cut(
    housing["median_income"],
    bins=[0.,1.5,3.0,4.5,6.,np.inf],
    labels=[1,2,3,4,5]
)

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_idx, test_idx in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_idx]
    strat_test_set = housing.loc[test_idx]

housing.plot(
    kind="scatter",
    x="longitude",
    y="latitude",
    alpha=0.4,
    s=housing["population"]/100,
    c="median_house_value",
    cmap="jet",
    colorbar=True,
    figsize=(10,7)
)
plt.show()

corr_matrix = housing.corr(numeric_only=True)
corr_matrix["median_house_value"].sort_values(ascending=False)
housing.plot(
    kind="scatter",
    x="median_income",
    y="median_house_value",
    alpha=0.1
)
plt.show()

housing["rooms_per_household"] = housing["total_rooms"] / housing["households"]
housing["bedrooms_per_room"] = housing["total_bedrooms"] / housing["total_rooms"]
housing["population_per_household"] = housing["population"] / housing["households"]
housing.corr(numeric_only=True)["median_house_value"].sort_values(ascending=False)

housing["total_bedrooms"] = housing["total_bedrooms"].fillna(
    housing["total_bedrooms"].median()
)

housing["ocean_proximity"].value_counts()
housing_encoded = pd.get_dummies(
    housing, columns=["ocean_proximity"]
)

housing_encoded.head()

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        rooms_per_household = X[:, 3] / X[:, 6]
        population_per_household = X[:, 5] / X[:, 6]
        bedrooms_per_room = X[:, 4] / X[:, 3]

        return np.c_[X,
                     rooms_per_household,
                     population_per_household,
                     bedrooms_per_room]

num_features = housing.drop("ocean_proximity", axis=1).columns
cat_features = ["ocean_proximity"]

num_pipeline = Pipeline([
    ("attribs_adder", CombinedAttributesAdder()),
    ("scaler", StandardScaler())
])

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_features),
    ("cat", OneHotEncoder(), cat_features)
])

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # X is a DataFrame inside ColumnTransformer
        rooms_per_household = X["total_rooms"] / X["households"]
        population_per_household = X["population"] / X["households"]
        bedrooms_per_room = X["total_bedrooms"] / X["total_rooms"]

        return np.c_[
            X.values,
            rooms_per_household,
            population_per_household,
            bedrooms_per_room
        ]

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # X is a DataFrame inside ColumnTransformer
        rooms_per_household = X["total_rooms"] / X["households"]
        population_per_household = X["population"] / X["households"]
        bedrooms_per_room = X["total_bedrooms"] / X["total_rooms"]

        return np.c_[
            X.values,
            rooms_per_household,
            population_per_household,
            bedrooms_per_room
        ]

num_features = housing.drop("ocean_proximity", axis=1).columns
cat_features = ["ocean_proximity"]

num_pipeline = Pipeline([
    ("attribs_adder", CombinedAttributesAdder()),
    ("scaler", StandardScaler())
])

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_features),
    ("cat", OneHotEncoder(), cat_features)
])

housing_prepared = full_pipeline.fit_transform(housing)
housing_prepared.shape