# -*- coding: utf-8 -*-
"""Lab 3 and 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQed9EWawlWl6ZLj9Aq4IORmtyL2ck2R
"""

import numpy as np
import pandas as pd
x = [8, 10, 12]
y = [10, 13, 16]

n = len(x)


mean_x = sum(x) / n
mean_y = sum(y) / n


sum_xy = sum(x[i] * y[i] for i in range(n))
sum_x_squared = sum(x[i] ** 2 for i in range(n))


numerator = sum_xy - n * mean_x * mean_y

denominator = sum_x_squared - n * mean_x ** 2

a1 = numerator / denominator

a0 = mean_y - a1 * mean_x

print("Slope (a1):", a1)
print("Intercept (a0):", a0)

x_new = 20
y_pred = a1 * x_new + a0

print("Predicted price for 20-inch pizza:", y_pred)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Upload file in Colab
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv(next(iter(uploaded)))

# Check dataset
print(df.head())
print(df.isnull().sum())   # Check for missing values

# If any missing values exist (optional safety step)
df = df.dropna()

# Define X and Y
X = df[['year']]
y = df['per capita income (US$)']

# Create and train model
model = LinearRegression()
model.fit(X, y)

# Predict income for year 2020
prediction_2020 = model.predict(pd.DataFrame({'year':[2020]}))

print("Predicted per capita income in 2020:", prediction_2020[0])

plt.scatter(X, y, color='blue')
plt.plot(X, model.predict(X), color='red')
plt.xlabel("Year")
plt.ylabel("Per Capita Income (US$)")
plt.title("Year vs Per Capita Income")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Upload file (Colab)
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv(next(iter(uploaded)))

# Check data
print(df.head())
print(df.isnull().sum())   # Check missing values

# If any missing values exist
df = df.dropna()

# Define features and target
X = df[['YearsExperience']]
y = df['Salary']

# Create model
model = LinearRegression()
model.fit(X, y)

# Predict salary for 12 years experience
prediction = model.predict(pd.DataFrame({'YearsExperience':[12]}))

plt.scatter(X, y, color='blue')
plt.plot(X, model.predict(X), color='red')
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Experience vs Salary")
plt.show()

# Import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Upload file
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv('1000_Companies.csv')

print(df.head())
print(df.info())

# -----------------------------
# Data Preprocessing
# -----------------------------

# Separate features and target
X = df[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]
y = df['Profit']

# One Hot Encoding for State column
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(drop='first'), ['State'])
    ],
    remainder='passthrough'
)

X = ct.fit_transform(X)

# Train model
model = LinearRegression()
model.fit(X, y)

# -----------------------------
# Prediction
# -----------------------------

# Order must match transformed structure
# Since drop='first', one state column is removed to avoid dummy variable trap

new_data = pd.DataFrame({
    'R&D Spend': [91694.48],
    'Administration': [515841.3],
    'Marketing Spend': [11931.24],
    'State': ['Florida']
})

new_data_transformed = ct.transform(new_data)

profit_prediction = model.predict(new_data_transformed)

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from google.colab import files

# Upload and read file
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)))

print(df.head())
print(df.info())

# Fill missing experience
df['experience'] = df['experience'].fillna(0)

# Convert text to numbers
df['experience'] = df['experience'].replace({
    'zero':0,'one':1,'two':2,'three':3,'four':4,
    'five':5,'six':6,'seven':7,'eight':8,
    'nine':9,'ten':10,'eleven':11,'twelve':12
}).astype(float)

# Fill missing test scores
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(
    df['test_score(out of 10)'].median()
)

# Features and target
X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]
y = df['salary($)']

# Train model
model = LinearRegression()
model.fit(X, y)

# Predictions
pred1 = model.predict(pd.DataFrame({
    'experience':[2],
    'test_score(out of 10)':[9],
    'interview_score(out of 10)':[6]
}))

pred2 = model.predict(pd.DataFrame({
    'experience':[12],
    'test_score(out of 10)':[10],
    'interview_score(out of 10)':[10]
}))

print("Predicted Salary (2yr,9,6):", pred1[0])
print("Predicted Salary (12yr,10,10):", pred2[0])